stages:
  - build

variables:
  REGISTRY: "registry.gitlab.com/laravel3605010/klublog"
  CONTAINER_PREFIX: "klublog"

before_script:
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

dev_build:
  stage: build
  tags:
    - dev
  only:
    - develop
  script:
    - docker build --build-arg NODE_ENV="dev" -t "$REGISTRY/dev/app:$CI_COMMIT_SHA" -f ./_docker/gitlab/app/Dockerfile .
    - docker push "$REGISTRY/dev/app:$CI_COMMIT_SHA"

dev_deploy:
  stage: deploy
  tags:
    - dev
  only:
    - develop
    - tags
  script:
    - docker stop $(docker ps -a | grep ${CONTAINER_PREFIX}_ | awk '{print $1}') || true
    - docker rm $(docker ps -a | grep ${CONTAINER_PREFIX}_ | awk '{print $1}') || true
    - docker volume rm $(docker volume ls | grep ${CONTAINER_PREFIX}_ | awk '{print $2}') || true
    - docker compose -p $CONTAINER_PREFIX -f docker-compose.dev.yml up -d
    - docker exec ${CONTAINER_PREFIX}_app composer update
    - docker exec ${CONTAINER_PREFIX}_app composer install
    - docker exec ${CONTAINER_PREFIX}_app php artisan migrate
    - docker exec ${CONTAINER_PREFIX}_app php artisan cache:clear
    - docker exec ${CONTAINER_PREFIX}_app php artisan config:cache
    - docker exec ${CONTAINER_PREFIX}_app php artisan route:cache
    - docker system prune -af

prod_deploy:
  stage: deploy
  tags:
    - prod
  only:
    - tags
  when: manual
  script:
    - docker stop $(docker ps -a | grep ${CONTAINER_PREFIX}_ | awk '{print $1}') || true
    - docker rm $(docker ps -a | grep ${CONTAINER_PREFIX}_ | awk '{print $1}') || true
    - docker volume rm $(docker volume ls | grep ${CONTAINER_PREFIX}_ | awk '{print $2}') || true
    - docker compose -p $CONTAINER_PREFIX -f docker-compose.prod.yml up -d
    - docker exec ${CONTAINER_PREFIX}_app composer update
    - docker exec ${CONTAINER_PREFIX}_app composer install
    - docker exec ${CONTAINER_PREFIX}_app php artisan migrate
    - docker exec ${CONTAINER_PREFIX}_app php artisan cache:clear
    - docker exec ${CONTAINER_PREFIX}_app php artisan config:cache
    - docker exec ${CONTAINER_PREFIX}_app php artisan route:cache
    - docker system prune -af

prod_clear_docker:
  stage: clear
  tags:
    - prod
  only:
    - tags
  when: manual
  script:
    - docker system prune -af

dev_clear_docker:
  stage: clear
  tags:
    - dev
  only:
    - develop
    - tags
  when: manual
  script:
    - docker system prune -af
